cam-id: 208
conn-string: "0.mp4"
analysis-time-delta: 0.25
ds-info:
  cropping:
    x:
      - 465
      - 1280
    y:
      - 0
      - 720
  pipe-model: 'models/best_seg_208.pt'
  line-start: 
    - 400
    - 1280
  line-end:
    - 400
    - 0
  dia-handler: LIST
  ratios: 
    px_ratio: 3.7
    abs_limits: 
      100:
        - 22
        - 30
      150:
        - 30
        - 37
      200:
        - 37
        - 46
      250:
        - 46
        - 52
  possible_dias:
    - 100
    - 150
    - 200
    - 250
    - 300
queue-url: https://sqs.ap-south-1.amazonaws.com/438957390193/sqs_esldip-local_dipcounter_ccm1_live.fifo